(component
  (type (;0;)
    (instance
      (export (;0;) "x" (type (sub resource)))
    )
  )
  (import "test:shared/types" (instance (;0;) (type 0)))
  (alias export 0 "x" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "x" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "f" (func (type 3)))
    )
  )
  (import "test:foo/i" (instance (;1;) (type 2)))
  (type (;3;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "x" (type (sub resource)))
        )
      )
      (import "test:shared/types" (instance (;0;) (type 0)))
      (alias export 0 "x" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "x" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (import "test:foo/i" (instance (;1;) (type 2)))
      (alias export 0 "x" (type (;3;)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (export (;1;) "x" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (export (;2;) "test:foo/i" (instance (type 4)))
    )
  )
  (import "unlocked-dep=<test:foo>" (component (;0;) (type 3)))
  (instance (;2;) (instantiate 0
      (with "test:shared/types" (instance 0))
      (with "test:foo/i" (instance 1))
    )
  )
  (alias export 2 "test:foo/i" (instance (;3;)))
  (instance (;4;) (instantiate 0
      (with "test:foo/i" (instance 3))
      (with "test:shared/types" (instance 0))
    )
  )
)
