(component
  (type (;0;)
    (instance
      (export (;0;) "x" (type (sub resource)))
    )
  )
  (import "foo:dependency/types" (instance (;0;) (type 0)))
  (alias export 0 "x" (type (;1;)))
  (import "x" (type (;2;) (eq 1)))
  (alias export 0 "x" (type (;3;)))
  (type (;4;)
    (instance
      (alias outer 1 3 (type (;0;)))
      (export (;1;) "x" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "my-func" (func (type 3)))
    )
  )
  (import "foo:test-import/my-interface" (instance (;1;) (type 4)))
  (type (;5;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "x" (type (sub resource)))
        )
      )
      (export (;0;) "foo:dependency/types" (instance (type 0)))
    )
  )
  (import "unlocked-dep=<test:bar>" (component (;0;) (type 5)))
  (instance (;2;) (instantiate 0))
  (alias export 1 "my-func" (func (;0;)))
  (alias export 2 "foo:dependency/types" (instance (;3;)))
  (type (;6;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "x" (type (sub resource)))
        )
      )
      (import "foo:dependency/types" (instance (;0;) (type 0)))
      (alias outer 1 3 (type (;1;)))
      (import "x" (type (;2;) (eq 1)))
      (type (;3;) (own 2))
      (type (;4;) (func (result 3)))
      (import "my-func" (func (;0;) (type 4)))
    )
  )
  (import "unlocked-dep=<test:baz>" (component (;1;) (type 6)))
  (instance (;4;) (instantiate 1
      (with "foo:dependency/types" (instance 3))
      (with "my-func" (func 0))
      (with "x" (type 2))
    )
  )
)
