(component
  (type (;0;)
    (instance
      (export (;0;) "fields" (type (sub resource)))
      (export (;1;) "headers" (type (eq 0)))
    )
  )
  (import "test:comp/types" (instance (;0;) (type 0)))
  (alias export 0 "headers" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "headers" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "get-headers" (func (type 3)))
    )
  )
  (import "test:comp/incoming-request" (instance (;1;) (type 2)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (result i32)))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (import "test:comp/types" "[resource-drop]fields" (func (;0;) (type 0)))
    (import "test:comp/incoming-request" "get-headers" (func (;1;) (type 1)))
    (func (;2;) (type 2) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 2))
    (@producers
      (processed-by "wit-component" "0.203.0")
    )
  )
  (alias export 0 "fields" (type (;3;)))
  (core func (;0;) (canon resource.drop 3))
  (core instance (;0;)
    (export "[resource-drop]fields" (func 0))
  )
  (alias export 1 "get-headers" (func (;0;)))
  (core func (;1;) (canon lower (func 0)))
  (core instance (;1;)
    (export "get-headers" (func 1))
  )
  (core instance (;2;) (instantiate 0
      (with "test:comp/types" (instance 0))
      (with "test:comp/incoming-request" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 2 "cabi_realloc" (core func (;2;)))
  (@producers
    (processed-by "wit-component" "0.203.0")
  )
)
