(component
  (import "x" (type (;0;) (sub resource)))
  (import "y" (type (;1;) (eq 0)))
  (type (;2;) (own 0))
  (type (;3;) (own 1))
  (type (;4;) (func (param "x" 2) (result 3)))
  (import "f" (func (;0;) (type 4)))
  (type (;5;)
    (component
      (import "x" (type (;0;) (sub resource)))
      (import "y" (type (;1;) (eq 0)))
      (type (;2;) (own 0))
      (type (;3;) (own 1))
      (type (;4;) (func (param "x" 2) (result 3)))
      (import "f" (func (;0;) (type 4)))
    )
  )
  (import "unlocked-dep=<test:foo>" (component (;0;) (type 5)))
  (instance (;0;) (instantiate 0
      (with "x" (type 0))
      (with "y" (type 1))
      (with "f" (func 0))
    )
  )
)
