(component
  (type (;0;)
    (instance
      (type (;0;) (record (field "x" s32)))
      (export (;1;) "point" (type (eq 0)))
    )
  )
  (import "test:prod/ext" (instance (;0;) (type 0)))
  (alias export 0 "point" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "point" (type (eq 0)))
      (type (;2;) (record (field "inner" 1)))
      (export (;3;) "region" (type (eq 2)))
    )
  )
  (import "test:prod/defs" (instance (;1;) (type 2)))
  (type (;3;) (record (field "inner" 1)))
  (import "region" (type (;4;) (eq 3)))
  (type (;5;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "x" s32)))
          (export (;1;) "point" (type (eq 0)))
        )
      )
      (import "test:prod/ext" (instance (;0;) (type 0)))
      (alias export 0 "point" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "point" (type (eq 0)))
          (type (;2;) (record (field "inner" 1)))
          (export (;3;) "region" (type (eq 2)))
        )
      )
      (import "test:prod/defs" (instance (;1;) (type 2)))
      (type (;3;) (record (field "inner" 1)))
      (import "region" (type (;4;) (eq 3)))
      (type (;5;) (func (result 4)))
      (export (;0;) "make" (func (type 5)))
      (alias export 0 "point" (type (;6;)))
      (type (;7;)
        (instance
          (alias outer 1 6 (type (;0;)))
          (export (;1;) "point" (type (eq 0)))
          (type (;2;) (record (field "inner" 1)))
          (export (;3;) "region" (type (eq 2)))
        )
      )
      (export (;2;) "test:prod/defs" (instance (type 7)))
    )
  )
  (import "unlocked-dep=<test:prod>" (component (;0;) (type 5)))
  (instance (;2;) (instantiate 0
      (with "test:prod/ext" (instance 0))
      (with "test:prod/defs" (instance 1))
      (with "region" (type 4))
    )
  )
  (alias export 2 "test:prod/defs" (instance (;3;)))
  (alias export 2 "make" (func (;0;)))
  (type (;6;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "x" s32)))
          (export (;1;) "point" (type (eq 0)))
        )
      )
      (import "test:prod/ext" (instance (;0;) (type 0)))
      (alias export 0 "point" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "point" (type (eq 0)))
          (type (;2;) (record (field "inner" 1)))
          (export (;3;) "region" (type (eq 2)))
        )
      )
      (import "test:prod/defs" (instance (;1;) (type 2)))
      (type (;3;) (record (field "inner" 1)))
      (import "region" (type (;4;) (eq 3)))
      (type (;5;) (func (result 4)))
      (import "make" (func (;0;) (type 5)))
      (type (;6;) (func (result s32)))
      (export (;1;) "run" (func (type 6)))
    )
  )
  (import "unlocked-dep=<test:cons>" (component (;1;) (type 6)))
  (instance (;4;) (instantiate 1
      (with "make" (func 0))
      (with "test:prod/defs" (instance 3))
      (with "test:prod/ext" (instance 0))
      (with "region" (type 4))
    )
  )
  (alias export 4 "run" (func (;1;)))
  (export (;2;) "run" (func 1))
)
