(component
  (type (;0;)
    (instance
      (export (;0;) "r" (type (sub resource)))
      (export (;1;) "s" (type (sub resource)))
    )
  )
  (import "foo:bar/types@0.2.1" (instance (;0;) (type 0)))
  (alias export 0 "r" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "r" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (param "x" 2)))
      (export (;0;) "do-something" (func (type 3)))
    )
  )
  (import "foo:bar/api@0.2.1" (instance (;1;) (type 2)))
  (type (;3;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "r" (type (sub resource)))
        )
      )
      (import "foo:bar/types@0.2.0" (instance (;0;) (type 0)))
      (alias export 0 "r" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "r" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (param "x" 2)))
          (export (;0;) "do-something" (func (type 3)))
        )
      )
      (import "foo:bar/api@0.2.0" (instance (;1;) (type 2)))
    )
  )
  (import "unlocked-dep=<test:a>" (component (;0;) (type 3)))
  (instance (;2;) (instantiate 0
      (with "foo:bar/types@0.2.0" (instance 0))
      (with "foo:bar/api@0.2.0" (instance 1))
    )
  )
  (type (;4;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "r" (type (sub resource)))
          (export (;1;) "s" (type (sub resource)))
        )
      )
      (import "foo:bar/types@0.2.1" (instance (;0;) (type 0)))
      (alias export 0 "r" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "r" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (param "x" 2)))
          (export (;0;) "do-something" (func (type 3)))
        )
      )
      (import "foo:bar/api@0.2.1" (instance (;1;) (type 2)))
    )
  )
  (import "unlocked-dep=<test:b>" (component (;1;) (type 4)))
  (instance (;3;) (instantiate 1
      (with "foo:bar/types@0.2.1" (instance 0))
      (with "foo:bar/api@0.2.1" (instance 1))
    )
  )
)
