(component
  (type (;0;)
    (instance
      (type (;0;) (record (field "x" s32)))
      (export (;1;) "point" (type (eq 0)))
    )
  )
  (import "test:lib/shapes" (instance (;0;) (type 0)))
  (alias export 0 "point" (type (;1;)))
  (type (;2;) (record (field "origin" 1)))
  (import "region" (type (;3;) (eq 2)))
  (type (;4;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "x" s32)))
          (export (;1;) "point" (type (eq 0)))
        )
      )
      (import "test:lib/shapes" (instance (;0;) (type 0)))
      (alias export 0 "point" (type (;1;)))
      (type (;2;) (record (field "origin" 1)))
      (import "region" (type (;3;) (eq 2)))
      (type (;4;) (func (result s32)))
      (export (;0;) "run" (func (type 4)))
    )
  )
  (import "unlocked-dep=<test:m>" (component (;0;) (type 4)))
  (instance (;1;) (instantiate 0
      (with "test:lib/shapes" (instance 0))
      (with "region" (type 3))
    )
  )
  (alias export 1 "run" (func (;0;)))
  (export (;1;) "run" (func 0))
)
