(component
  (type (;0;)
    (instance)
  )
  (import "i1" (instance (;0;) (type 0)))
  (type (;1;)
    (instance
      (type (;0;) (func))
      (export (;0;) "a" (func (type 0)))
      (type (;1;) (func))
      (export (;1;) "b" (func (type 1)))
    )
  )
  (import "merged" (instance (;1;) (type 1)))
  (type (;2;)
    (instance)
  )
  (import "i2" (instance (;2;) (type 2)))
  (type (;3;) (func))
  (import "my-foo" (func $my-foo (;0;) (type 3)))
  (type (;4;)
    (component
      (type (;0;) (func))
      (import "foo" (func (;0;) (type 0)))
      (type (;1;)
        (instance)
      )
      (import "i1" (instance (;0;) (type 1)))
      (type (;2;)
        (instance
          (type (;0;) (func))
          (export (;0;) "a" (func (type 0)))
          (type (;1;) (func))
          (export (;1;) "b" (func (type 1)))
        )
      )
      (import "merged" (instance (;1;) (type 2)))
      (export (;1;) "bar" (func (type 0)))
      (type (;3;) (func))
      (export (;4;) "f" (type (eq 3)))
    )
  )
  (import "unlocked-dep=<test:foo>" (component (;0;) (type 4)))
  (instance $foo (;3;) (instantiate 0
      (with "foo" (func $my-foo))
      (with "i1" (instance 0))
      (with "merged" (instance 1))
    )
  )
  (alias export $foo "bar" (func $e (;1;)))
  (type (;5;)
    (component
      (type (;0;) (func))
      (import "e" (func (;0;) (type 0)))
      (type (;1;)
        (instance)
      )
      (import "i2" (instance (;0;) (type 1)))
      (type (;2;)
        (instance
          (type (;0;) (func))
          (export (;0;) "a" (func (type 0)))
        )
      )
      (import "merged" (instance (;1;) (type 2)))
      (export (;1;) "e" (func (type 0)))
    )
  )
  (import "unlocked-dep=<test:bar>" (component (;1;) (type 5)))
  (instance $bar (;4;) (instantiate 1
      (with "e" (func $e))
      (with "i2" (instance 2))
      (with "merged" (instance 1))
    )
  )
  (alias export $bar "e" (func $e2 (;2;)))
  (export (;3;) "e2" (func $e2))
)
