(component
  (type (;0;)
    (instance
      (type (;0;) (map string string))
      (export (;1;) "headers" (type (eq 0)))
      (type (;2;) (map string u32))
      (type (;3;) (option u32))
      (type (;4;) (func (param "m" 2) (result 3)))
      (export (;0;) "lookup" (func (type 4)))
      (type (;5;) (list u8))
      (type (;6;) (map string 5))
      (type (;7;) (func (param "h" 1) (result 6)))
      (export (;1;) "bundle" (func (type 7)))
    )
  )
  (import "test:foo/i" (instance (;0;) (type 0)))
  (type (;1;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (map string string))
          (export (;1;) "headers" (type (eq 0)))
          (type (;2;) (map string u32))
          (type (;3;) (option u32))
          (type (;4;) (func (param "m" 2) (result 3)))
          (export (;0;) "lookup" (func (type 4)))
          (type (;5;) (list u8))
          (type (;6;) (map string 5))
          (type (;7;) (func (param "h" 1) (result 6)))
          (export (;1;) "bundle" (func (type 7)))
        )
      )
      (import "test:foo/i" (instance (;0;) (type 0)))
      (type (;1;)
        (instance
          (type (;0;) (map string string))
          (export (;1;) "headers" (type (eq 0)))
          (type (;2;) (map string u32))
          (type (;3;) (option u32))
          (type (;4;) (func (param "m" 2) (result 3)))
          (export (;0;) "lookup" (func (type 4)))
          (type (;5;) (list u8))
          (type (;6;) (map string 5))
          (type (;7;) (func (param "h" 1) (result 6)))
          (export (;1;) "bundle" (func (type 7)))
        )
      )
      (export (;1;) "test:foo/i" (instance (type 1)))
    )
  )
  (import "unlocked-dep=<test:foo>" (component (;0;) (type 1)))
  (instance (;1;) (instantiate 0
      (with "test:foo/i" (instance 0))
    )
  )
  (alias export 1 "test:foo/i" (instance (;2;)))
  (instance (;3;) (instantiate 0
      (with "test:foo/i" (instance 2))
    )
  )
  (alias export 3 "test:foo/i" (instance (;4;)))
  (export (;5;) "test:foo/i" (instance 4))
)
