(component
  (type (;0;)
    (instance
      (export (;0;) "x" (type (sub resource)))
    )
  )
  (import "foo:bar/baz" (instance (;0;) (type 0)))
  (alias export 0 "x" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "x" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "f" (func (type 3)))
    )
  )
  (import "foo:bar/qux" (instance (;1;) (type 2)))
  (component (;0;)
    (type (;0;)
      (instance
        (export (;0;) "x" (type (sub resource)))
      )
    )
    (import "foo:bar/baz" (instance (;0;) (type 0)))
    (alias export 0 "x" (type (;1;)))
    (type (;2;)
      (instance
        (alias outer 1 1 (type (;0;)))
        (export (;1;) "x" (type (eq 0)))
        (type (;2;) (own 1))
        (type (;3;) (func (result 2)))
        (export (;0;) "f" (func (type 3)))
      )
    )
    (import "foo:bar/qux" (instance (;1;) (type 2)))
    (core module (;0;)
      (type (;0;) (func (param i32)))
      (type (;1;) (func (result i32)))
      (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
      (import "foo:bar/baz" "[resource-drop]x" (func (;0;) (type 0)))
      (import "foo:bar/qux" "f" (func (;1;) (type 1)))
      (func (;2;) (type 1) (result i32)
        unreachable
      )
      (func (;3;) (type 2) (param i32 i32 i32 i32) (result i32)
        unreachable
      )
      (memory (;0;) 0)
      (export "foo:bar/qux#f" (func 2))
      (export "memory" (memory 0))
      (export "cabi_realloc" (func 3))
      (@producers
        (processed-by "wit-component" "0.201.0")
      )
    )
    (alias export 0 "x" (type (;3;)))
    (core func (;0;) (canon resource.drop 3))
    (core instance (;0;)
      (export "[resource-drop]x" (func 0))
    )
    (alias export 1 "f" (func (;0;)))
    (core func (;1;) (canon lower (func 0)))
    (core instance (;1;)
      (export "f" (func 1))
    )
    (core instance (;2;) (instantiate 0
        (with "foo:bar/baz" (instance 0))
        (with "foo:bar/qux" (instance 1))
      )
    )
    (alias core export 2 "memory" (core memory (;0;)))
    (alias core export 2 "cabi_realloc" (core func (;2;)))
    (alias export 0 "x" (type (;4;)))
    (type (;5;) (own 4))
    (type (;6;) (func (result 5)))
    (alias core export 2 "foo:bar/qux#f" (core func (;3;)))
    (func (;1;) (type 6) (canon lift (core func 3)))
    (alias export 0 "x" (type (;7;)))
    (component (;0;)
      (import "import-type-x" (type (;0;) (sub resource)))
      (import "import-type-x0" (type (;1;) (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (import "import-func-f" (func (;0;) (type 3)))
      (export (;4;) "x" (type 0))
      (type (;5;) (own 4))
      (type (;6;) (func (result 5)))
      (export (;1;) "f" (func 0) (func (type 6)))
    )
    (instance (;2;) (instantiate 0
        (with "import-func-f" (func 1))
        (with "import-type-x" (type 7))
        (with "import-type-x0" (type 4))
      )
    )
    (export (;3;) "foo:bar/qux" (instance 2))
    (@producers
      (processed-by "wit-component" "0.201.0")
    )
  )
  (instance $component2 (;2;) (instantiate 0
      (with "foo:bar/baz" (instance 0))
      (with "foo:bar/qux" (instance 1))
    )
  )
  (alias export $component2 "foo:bar/qux" (instance $alias (;3;)))
  (component (;1;)
    (type (;0;)
      (instance
        (export (;0;) "x" (type (sub resource)))
      )
    )
    (import "foo:bar/baz" (instance (;0;) (type 0)))
    (alias export 0 "x" (type (;1;)))
    (type (;2;)
      (instance
        (alias outer 1 1 (type (;0;)))
        (export (;1;) "x" (type (eq 0)))
        (type (;2;) (own 1))
        (type (;3;) (func (result 2)))
        (export (;0;) "f" (func (type 3)))
      )
    )
    (import "foo:bar/qux" (instance (;1;) (type 2)))
    (core module (;0;)
      (type (;0;) (func (param i32)))
      (type (;1;) (func (result i32)))
      (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
      (import "foo:bar/baz" "[resource-drop]x" (func (;0;) (type 0)))
      (import "foo:bar/qux" "f" (func (;1;) (type 1)))
      (func (;2;) (type 1) (result i32)
        unreachable
      )
      (func (;3;) (type 2) (param i32 i32 i32 i32) (result i32)
        unreachable
      )
      (memory (;0;) 0)
      (export "foo:bar/qux#f" (func 2))
      (export "memory" (memory 0))
      (export "cabi_realloc" (func 3))
      (@producers
        (processed-by "wit-component" "0.201.0")
      )
    )
    (alias export 0 "x" (type (;3;)))
    (core func (;0;) (canon resource.drop 3))
    (core instance (;0;)
      (export "[resource-drop]x" (func 0))
    )
    (alias export 1 "f" (func (;0;)))
    (core func (;1;) (canon lower (func 0)))
    (core instance (;1;)
      (export "f" (func 1))
    )
    (core instance (;2;) (instantiate 0
        (with "foo:bar/baz" (instance 0))
        (with "foo:bar/qux" (instance 1))
      )
    )
    (alias core export 2 "memory" (core memory (;0;)))
    (alias core export 2 "cabi_realloc" (core func (;2;)))
    (alias export 0 "x" (type (;4;)))
    (type (;5;) (own 4))
    (type (;6;) (func (result 5)))
    (alias core export 2 "foo:bar/qux#f" (core func (;3;)))
    (func (;1;) (type 6) (canon lift (core func 3)))
    (alias export 0 "x" (type (;7;)))
    (component (;0;)
      (import "import-type-x" (type (;0;) (sub resource)))
      (import "import-type-x0" (type (;1;) (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (import "import-func-f" (func (;0;) (type 3)))
      (export (;4;) "x" (type 0))
      (type (;5;) (own 4))
      (type (;6;) (func (result 5)))
      (export (;1;) "f" (func 0) (func (type 6)))
    )
    (instance (;2;) (instantiate 0
        (with "import-func-f" (func 1))
        (with "import-type-x" (type 7))
        (with "import-type-x0" (type 4))
      )
    )
    (export (;3;) "foo:bar/qux" (instance 2))
    (@producers
      (processed-by "wit-component" "0.201.0")
    )
  )
  (instance $component1 (;4;) (instantiate 1
      (with "foo:bar/qux" (instance $alias))
      (with "foo:bar/baz" (instance 0))
    )
  )
  (alias export $component1 "foo:bar/qux" (instance $export (;5;)))
  (export (;6;) "foo:bar/qux" (instance $export))
)
