(component
  (type (;0;)
    (instance
      (export (;0;) "x" (type (sub resource)))
    )
  )
  (import "foo:bar/baz" (instance (;0;) (type 0)))
  (alias export 0 "x" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "x" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "f" (func (type 3)))
    )
  )
  (import "foo:bar/qux" (instance (;1;) (type 2)))
  (type (;3;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "x" (type (sub resource)))
        )
      )
      (import "foo:bar/baz" (instance (;0;) (type 0)))
      (alias export 0 "x" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "x" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (import "foo:bar/qux" (instance (;1;) (type 2)))
      (alias export 0 "x" (type (;3;)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (export (;1;) "x" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (export (;2;) "foo:bar/qux" (instance (type 4)))
    )
  )
  (import "unlocked-dep=<test:bar>" (component (;0;) (type 3)))
  (instance $component2 (;2;) (instantiate 0
      (with "foo:bar/baz" (instance 0))
      (with "foo:bar/qux" (instance 1))
    )
  )
  (alias export $component2 "foo:bar/qux" (instance $alias (;3;)))
  (type (;4;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "x" (type (sub resource)))
        )
      )
      (import "foo:bar/baz" (instance (;0;) (type 0)))
      (alias export 0 "x" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "x" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (import "foo:bar/qux" (instance (;1;) (type 2)))
      (alias export 0 "x" (type (;3;)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (export (;1;) "x" (type (eq 0)))
          (type (;2;) (own 1))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (export (;2;) "foo:bar/qux" (instance (type 4)))
    )
  )
  (import "unlocked-dep=<test:foo>" (component (;1;) (type 4)))
  (instance $component1 (;4;) (instantiate 1
      (with "foo:bar/qux" (instance $alias))
      (with "foo:bar/baz" (instance 0))
    )
  )
  (alias export $component1 "foo:bar/qux" (instance $export (;5;)))
  (export (;6;) "foo:bar/qux" (instance $export))
)
