(component
  (type (;0;)
    (instance
      (type (;0;) (record (field "foo" string)))
      (export (;1;) "my-record" (type (eq 0)))
      (type (;2;) (variant (case "x")))
      (export (;3;) "my-variant" (type (eq 2)))
    )
  )
  (import "foo:dependency/types" (instance (;0;) (type 0)))
  (alias export 0 "my-variant" (type (;1;)))
  (type (;2;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export (;1;) "my-variant" (type (eq 0)))
      (type (;2;) (func (result 1)))
      (export (;0;) "my-func" (func (type 2)))
    )
  )
  (import "foo:test-import/my-interface" (instance (;1;) (type 2)))
  (type (;3;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "foo" string)))
          (export (;1;) "my-record" (type (eq 0)))
        )
      )
      (import "foo:dependency/types" (instance (;0;) (type 0)))
      (alias export 0 "my-record" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "my-record" (type (eq 0)))
          (type (;2;) (func (result 1)))
          (export (;0;) "my-func" (func (type 2)))
        )
      )
      (export (;1;) "foo:component/my-interface" (instance (type 2)))
    )
  )
  (import "unlocked-dep=<test:component>" (component (;0;) (type 3)))
  (instance (;2;) (instantiate 0
      (with "foo:dependency/types" (instance 0))
    )
  )
)
